import AVFoundation
import Foundation

/// Original, offline instrumental loops generated by Vertex2 itself.
/// They are deliberately independent from project/timeline audio and are never exported.
enum FocusMusicTrack: String, CaseIterable, Identifiable, Sendable {
    case quietDesk
    case midnightRender
    case rainyTimeline
    case warmKeyframes
    case softCircuit
    case deepFocus

    var id: String { rawValue }

    var title: String {
        switch self {
        case .quietDesk: "Quiet Desk"
        case .midnightRender: "Midnight Render"
        case .rainyTimeline: "Rainy Timeline"
        case .warmKeyframes: "Warm Keyframes"
        case .softCircuit: "Soft Circuit"
        case .deepFocus: "Deep Focus"
        }
    }

    var subtitle: String {
        switch self {
        case .quietDesk: "soft keys • calm lo-fi"
        case .midnightRender: "dark pad • slow pulse"
        case .rainyTimeline: "air texture • gentle keys"
        case .warmKeyframes: "warm chords • mellow plucks"
        case .softCircuit: "clean synth • light motion"
        case .deepFocus: "minimal pad • low distraction"
        }
    }

    var bpm: Int { Int(configuration.bpm.rounded()) }

    fileprivate var configuration: FocusMusicConfiguration {
        switch self {
        case .quietDesk:
            FocusMusicConfiguration(rootMIDI: 50, progression: [0, 5, 3, 7], chordIntervals: [0, 3, 7, 10], bpm: 72, brightness: 0.16, air: 0.0018, pluck: 0.050, phase: 0.1)
        case .midnightRender:
            FocusMusicConfiguration(rootMIDI: 45, progression: [0, 3, 7, 5], chordIntervals: [0, 3, 7, 10], bpm: 64, brightness: 0.08, air: 0.0010, pluck: 0.032, phase: 1.3)
        case .rainyTimeline:
            FocusMusicConfiguration(rootMIDI: 48, progression: [0, 7, 5, 3], chordIntervals: [0, 4, 7, 11], bpm: 68, brightness: 0.13, air: 0.0042, pluck: 0.040, phase: 2.4)
        case .warmKeyframes:
            FocusMusicConfiguration(rootMIDI: 53, progression: [0, 4, 9, 5], chordIntervals: [0, 4, 7, 11], bpm: 76, brightness: 0.20, air: 0.0015, pluck: 0.057, phase: 0.7)
        case .softCircuit:
            FocusMusicConfiguration(rootMIDI: 47, progression: [0, 5, 8, 3], chordIntervals: [0, 3, 7, 10], bpm: 80, brightness: 0.24, air: 0.0012, pluck: 0.060, phase: 1.9)
        case .deepFocus:
            FocusMusicConfiguration(rootMIDI: 43, progression: [0, 5, 2, 7], chordIntervals: [0, 3, 7, 10], bpm: 60, brightness: 0.05, air: 0.0007, pluck: 0.020, phase: 2.9)
        }
    }
}

private struct FocusMusicConfiguration: Sendable {
    let rootMIDI: Int
    let progression: [Int]
    let chordIntervals: [Int]
    let bpm: Double
    let brightness: Double
    let air: Double
    let pluck: Double
    let phase: Double
}

/// Small deterministic synthesizer used instead of bundled copyrighted songs.
/// It creates one seamless-ish PCM loop on a utility task, then AVAudioPlayer loops
/// that already-rendered buffer with negligible editing-time CPU overhead.
enum FocusMusicSynthesizer {
    static let sampleRate = 32_000
    static let durationSeconds = 16.0

    static func render(track: FocusMusicTrack) -> Data {
        let config = track.configuration
        let frameCount = Int(Double(sampleRate) * durationSeconds)
        let segmentDuration = durationSeconds / Double(config.progression.count)
        let chordFrequencies = config.progression.map { offset in
            config.chordIntervals.map { interval in
                midiFrequency(config.rootMIDI + offset + interval)
            }
        }
        var samples = [Int16](repeating: 0, count: frameCount * 2)
        var noiseSeed = UInt64(truncatingIfNeeded: track.rawValue.utf8.reduce(0) { ($0 &* 131) &+ UInt64($1) }) | 1
        var smoothedNoise = 0.0
        let beatDuration = 60.0 / config.bpm
        let twoPi = Double.pi * 2

        for frame in 0..<frameCount {
            let time = Double(frame) / Double(sampleRate)
            let segment = min(Int(time / segmentDuration), chordFrequencies.count - 1)
            let segmentTime = time - Double(segment) * segmentDuration
            let frequencies = chordFrequencies[segment]
            let edgeFade = min(1.0, min(segmentTime, segmentDuration - segmentTime) / 0.16)
            let slowBreath = 0.82 + 0.18 * sin(twoPi * time / 7.5 + config.phase)

            var padLeft = 0.0
            var padRight = 0.0
            for (index, frequency) in frequencies.enumerated() {
                let weight = index == 0 ? 0.42 : 0.24
                let octave = index == 0 ? frequency * 0.5 : frequency
                padLeft += sin(twoPi * octave * time + Double(index) * 0.17) * weight
                padRight += sin(twoPi * octave * time + Double(index) * 0.17 + 0.035 + config.phase * 0.01) * weight
                if config.brightness > 0 {
                    padLeft += sin(twoPi * octave * 2 * time + 0.3) * weight * config.brightness
                    padRight += sin(twoPi * octave * 2 * time + 0.36) * weight * config.brightness
                }
            }
            padLeft *= edgeFade * slowBreath
            padRight *= edgeFade * slowBreath

            let beatIndex = Int(time / beatDuration)
            let beatTime = time - Double(beatIndex) * beatDuration
            let pluckFrequency = frequencies[beatIndex % frequencies.count] * 2.0
            let pluckAttack = min(1.0, beatTime / 0.012)
            let pluckEnvelope = pluckAttack * exp(-5.2 * beatTime)
            let pluck = (sin(twoPi * pluckFrequency * beatTime) + 0.22 * sin(twoPi * pluckFrequency * 2 * beatTime)) * pluckEnvelope * config.pluck

            noiseSeed = noiseSeed &* 6_364_136_223_846_793_005 &+ 1_442_695_040_888_963_407
            let rawNoise = Double(Int32(bitPattern: UInt32(truncatingIfNeeded: noiseSeed >> 32))) / Double(Int32.max)
            smoothedNoise += (rawNoise - smoothedNoise) * 0.035
            let air = smoothedNoise * config.air

            let loopFadeFrames = Double(sampleRate) * 0.10
            let loopFade = min(1.0, min(Double(frame), Double(frameCount - 1 - frame)) / loopFadeFrames)
            let pan = 0.5 + 0.12 * sin(twoPi * time / 11.0 + config.phase)
            let leftGain = sqrt(max(0.0, 1.0 - pan))
            let rightGain = sqrt(max(0.0, pan))
            let master = 0.23 * loopFade
            let left = (padLeft * leftGain + pluck * 0.82 + air) * master
            let right = (padRight * rightGain + pluck + air * 0.94) * master
            samples[frame * 2] = pcm16(left)
            samples[frame * 2 + 1] = pcm16(right)
        }

        return waveData(samples: samples, sampleRate: sampleRate)
    }

    private static func midiFrequency(_ note: Int) -> Double {
        440.0 * pow(2.0, Double(note - 69) / 12.0)
    }

    private static func pcm16(_ value: Double) -> Int16 {
        let clamped = min(max(value, -1), 1)
        return Int16((clamped * Double(Int16.max)).rounded())
    }

    private static func waveData(samples: [Int16], sampleRate: Int) -> Data {
        let channels: UInt16 = 2
        let bitsPerSample: UInt16 = 16
        let bytesPerSample = UInt32(bitsPerSample / 8)
        let dataByteCount = UInt32(samples.count) * bytesPerSample
        var result = Data()
        result.reserveCapacity(Int(44 + dataByteCount))

        func ascii(_ string: String) {
            result.append(contentsOf: string.utf8)
        }
        func u16(_ value: UInt16) {
            var little = value.littleEndian
            withUnsafeBytes(of: &little) { result.append(contentsOf: $0) }
        }
        func u32(_ value: UInt32) {
            var little = value.littleEndian
            withUnsafeBytes(of: &little) { result.append(contentsOf: $0) }
        }

        ascii("RIFF")
        u32(36 + dataByteCount)
        ascii("WAVE")
        ascii("fmt ")
        u32(16)
        u16(1)
        u16(channels)
        u32(UInt32(sampleRate))
        u32(UInt32(sampleRate) * UInt32(channels) * bytesPerSample)
        u16(channels * UInt16(bytesPerSample))
        u16(bitsPerSample)
        ascii("data")
        u32(dataByteCount)

        samples.withUnsafeBufferPointer { buffer in
            result.append(Data(buffer: buffer))
        }
        return result
    }
}

@MainActor
final class FocusMusicPlayer: ObservableObject {
    private enum DefaultsKey {
        static let track = "vertex.focusMusic.track.v1"
        static let volume = "vertex.focusMusic.volume.v1"
    }

    @Published private(set) var selectedTrack: FocusMusicTrack
    @Published private(set) var isPlaying = false
    @Published private(set) var isPreparing = false
    @Published private(set) var volume: Double
    @Published private(set) var errorMessage: String?

    private var audioPlayer: AVAudioPlayer?
    private var loadedTrack: FocusMusicTrack?
    private var renderGeneration = 0
    private let defaults: UserDefaults

    init(defaults: UserDefaults = .standard) {
        self.defaults = defaults
        selectedTrack = FocusMusicTrack(rawValue: defaults.string(forKey: DefaultsKey.track) ?? "") ?? .quietDesk
        if defaults.object(forKey: DefaultsKey.volume) == nil {
            volume = 0.32
        } else {
            volume = min(max(defaults.double(forKey: DefaultsKey.volume), 0), 0.8)
        }
    }

    func togglePlayback() {
        if isPlaying {
            audioPlayer?.pause()
            isPlaying = false
            return
        }
        if loadedTrack == selectedTrack, let audioPlayer {
            do {
                try activateSession()
                audioPlayer.volume = Float(volume)
                audioPlayer.play()
                isPlaying = true
                errorMessage = nil
            } catch {
                errorMessage = error.localizedDescription
            }
            return
        }
        prepare(track: selectedTrack, autoPlay: true)
    }

    func select(_ track: FocusMusicTrack) {
        guard track != selectedTrack else { return }
        selectedTrack = track
        defaults.set(track.rawValue, forKey: DefaultsKey.track)
        let shouldContinue = isPlaying
        if shouldContinue {
            audioPlayer?.stop()
            isPlaying = false
            prepare(track: track, autoPlay: true)
        }
    }

    func selectNext() {
        let tracks = FocusMusicTrack.allCases
        guard let index = tracks.firstIndex(of: selectedTrack) else { return }
        select(tracks[(index + 1) % tracks.count])
    }

    func selectPrevious() {
        let tracks = FocusMusicTrack.allCases
        guard let index = tracks.firstIndex(of: selectedTrack) else { return }
        select(tracks[(index - 1 + tracks.count) % tracks.count])
    }

    func setVolume(_ newValue: Double) {
        volume = min(max(newValue, 0), 0.8)
        audioPlayer?.volume = Float(volume)
        defaults.set(volume, forKey: DefaultsKey.volume)
    }

    private func prepare(track: FocusMusicTrack, autoPlay: Bool) {
        renderGeneration += 1
        let generation = renderGeneration
        isPreparing = true
        errorMessage = nil

        Task { [weak self] in
            let data = await Task.detached(priority: .utility) {
                FocusMusicSynthesizer.render(track: track)
            }.value
            guard let self, generation == self.renderGeneration else { return }
            do {
                let player = try AVAudioPlayer(data: data)
                player.numberOfLoops = -1
                player.volume = Float(self.volume)
                player.prepareToPlay()
                self.audioPlayer?.stop()
                self.audioPlayer = player
                self.loadedTrack = track
                self.isPreparing = false
                if autoPlay {
                    try self.activateSession()
                    player.play()
                    self.isPlaying = true
                }
            } catch {
                self.isPreparing = false
                self.isPlaying = false
                self.errorMessage = error.localizedDescription
            }
        }
    }

    private func activateSession() throws {
        let session = AVAudioSession.sharedInstance()
        try session.setCategory(.ambient, mode: .default, options: [.mixWithOthers])
        try session.setActive(true)
    }
}
