import AVFoundation
import Combine
import Foundation

/// Original offline instrumental loops generated by Vertex2 itself.
/// Focus Music is deliberately independent from project/timeline audio and is never exported.
enum FocusMusicTrack: String, CaseIterable, Identifiable, Sendable {
    case quietDesk
    case midnightRender
    case rainyTimeline
    case warmKeyframes
    case softCircuit
    case deepFocus
    case morningFlow
    case glassRain
    case neonStudy
    case analogNight
    case blueHour
    case pixelCafe
    case lucidLoop
    case softOrbit
    case cloudNotes
    case afterglow
    case silentMetro
    case lunarDesk
    case velvetCode
    case oceanMemory
    case lowGravity
    case paperStars
    case frozenKeys
    case finalExport

    var id: String { rawValue }
    var title: String { definition.title }
    var subtitle: String { definition.subtitle }
    var bpm: Int { Int(definition.configuration.bpm.rounded()) }
    fileprivate var configuration: FocusMusicConfiguration { definition.configuration }

    private var definition: FocusMusicDefinition {
        switch self {
        case .quietDesk: .init("Quiet Desk", "soft keys • calm lo-fi", 50, [0, 5, 3, 7], [0, 3, 7, 10], 72, 0.16, 0.0018, 0.050, 0.1)
        case .midnightRender: .init("Midnight Render", "dark pad • slow pulse", 45, [0, 3, 7, 5], [0, 3, 7, 10], 64, 0.08, 0.0010, 0.032, 1.3)
        case .rainyTimeline: .init("Rainy Timeline", "air texture • gentle keys", 48, [0, 7, 5, 3], [0, 4, 7, 11], 68, 0.13, 0.0042, 0.040, 2.4)
        case .warmKeyframes: .init("Warm Keyframes", "warm chords • mellow plucks", 53, [0, 4, 9, 5], [0, 4, 7, 11], 76, 0.20, 0.0015, 0.057, 0.7)
        case .softCircuit: .init("Soft Circuit", "clean synth • light motion", 47, [0, 5, 8, 3], [0, 3, 7, 10], 80, 0.24, 0.0012, 0.060, 1.9)
        case .deepFocus: .init("Deep Focus", "minimal pad • low distraction", 43, [0, 5, 2, 7], [0, 3, 7, 10], 60, 0.05, 0.0007, 0.020, 2.9)
        case .morningFlow: .init("Morning Flow", "clear bells • soft sunrise", 55, [0, 7, 9, 5], [0, 4, 7, 11], 82, 0.28, 0.0011, 0.065, 0.35)
        case .glassRain: .init("Glass Rain", "glassy notes • drifting mist", 52, [0, 5, 7, 2], [0, 4, 7, 9], 66, 0.31, 0.0038, 0.044, 1.05)
        case .neonStudy: .init("Neon Study", "neon pulse • clean bass", 46, [0, 3, 8, 5], [0, 3, 7, 10], 88, 0.30, 0.0008, 0.072, 1.55)
        case .analogNight: .init("Analog Night", "tape warmth • dusty pad", 44, [0, 5, 10, 7], [0, 3, 7, 10], 62, 0.07, 0.0030, 0.028, 2.1)
        case .blueHour: .init("Blue Hour", "wide pad • late-evening calm", 49, [0, 4, 7, 11], [0, 4, 7, 11], 70, 0.14, 0.0015, 0.038, 2.65)
        case .pixelCafe: .init("Pixel Café", "tiny plucks • cozy loop", 57, [0, 9, 5, 7], [0, 4, 7, 9], 92, 0.34, 0.0018, 0.078, 0.5)
        case .lucidLoop: .init("Lucid Loop", "floating chords • lucid pulse", 51, [0, 2, 7, 5], [0, 4, 7, 11], 74, 0.23, 0.0010, 0.052, 1.75)
        case .softOrbit: .init("Soft Orbit", "round bass • orbiting pad", 42, [0, 7, 3, 5], [0, 3, 7, 10], 58, 0.10, 0.0009, 0.024, 3.0)
        case .cloudNotes: .init("Cloud Notes", "airy fifths • cloud texture", 54, [0, 5, 9, 7], [0, 4, 7, 14], 78, 0.26, 0.0034, 0.047, 0.95)
        case .afterglow: .init("Afterglow", "warm shimmer • slow release", 50, [0, 9, 4, 5], [0, 4, 7, 11], 72, 0.27, 0.0017, 0.043, 2.3)
        case .silentMetro: .init("Silent Metro", "muted pulse • distant city", 45, [0, 5, 3, 10], [0, 3, 7, 10], 84, 0.12, 0.0022, 0.048, 1.4)
        case .lunarDesk: .init("Lunar Desk", "low pad • moonlit focus", 41, [0, 7, 5, 2], [0, 3, 7, 10], 56, 0.06, 0.0006, 0.018, 2.75)
        case .velvetCode: .init("Velvet Code", "velvet chords • subtle beat", 48, [0, 3, 8, 10], [0, 3, 7, 10], 86, 0.18, 0.0011, 0.058, 1.15)
        case .oceanMemory: .init("Ocean Memory", "slow swell • blue ambience", 46, [0, 5, 7, 3], [0, 4, 7, 11], 54, 0.09, 0.0046, 0.016, 2.55)
        case .lowGravity: .init("Low Gravity", "weightless pad • soft sub", 40, [0, 7, 10, 5], [0, 3, 7, 10], 52, 0.05, 0.0005, 0.014, 3.2)
        case .paperStars: .init("Paper Stars", "delicate plucks • bright air", 56, [0, 4, 7, 9], [0, 4, 7, 11], 90, 0.36, 0.0021, 0.082, 0.2)
        case .frozenKeys: .init("Frozen Keys", "icy keys • still atmosphere", 52, [0, 2, 5, 9], [0, 4, 7, 11], 68, 0.32, 0.0027, 0.045, 1.85)
        case .finalExport: .init("Final Export", "resolved chords • quiet finish", 53, [0, 5, 7, 0], [0, 4, 7, 11], 76, 0.22, 0.0012, 0.052, 0.65)
        }
    }
}

private struct FocusMusicDefinition: Sendable {
    let title: String
    let subtitle: String
    let configuration: FocusMusicConfiguration

    init(_ title: String, _ subtitle: String, _ rootMIDI: Int, _ progression: [Int], _ chordIntervals: [Int], _ bpm: Double, _ brightness: Double, _ air: Double, _ pluck: Double, _ phase: Double) {
        self.title = title
        self.subtitle = subtitle
        self.configuration = FocusMusicConfiguration(rootMIDI: rootMIDI, progression: progression, chordIntervals: chordIntervals, bpm: bpm, brightness: brightness, air: air, pluck: pluck, phase: phase)
    }
}

private struct FocusMusicConfiguration: Sendable {
    let rootMIDI: Int
    let progression: [Int]
    let chordIntervals: [Int]
    let bpm: Double
    let brightness: Double
    let air: Double
    let pluck: Double
    let phase: Double
}

enum FocusMusicPlaybackPolicy {
    static let category: AVAudioSession.Category = .playback
    static let options: AVAudioSession.CategoryOptions = [.mixWithOthers]
}

enum FocusMusicError: LocalizedError {
    case couldNotPrepare
    case couldNotStart

    var errorDescription: String? {
        switch self {
        case .couldNotPrepare: "Focus Music audio could not be prepared."
        case .couldNotStart: "Focus Music audio output could not start."
        }
    }
}

/// Small deterministic synthesizer used instead of bundled copyrighted songs.
/// It creates one stereo PCM loop and AVAudioPlayer repeats the rendered buffer.
enum FocusMusicSynthesizer {
    static let sampleRate = 32_000
    static let durationSeconds = 16.0

    static func render(track: FocusMusicTrack) -> Data {
        let config = track.configuration
        let frameCount = Int(Double(sampleRate) * durationSeconds)
        let segmentDuration = durationSeconds / Double(config.progression.count)
        let chordFrequencies = config.progression.map { offset in
            config.chordIntervals.map { interval in midiFrequency(config.rootMIDI + offset + interval) }
        }
        var samples = [Int16](repeating: 0, count: frameCount * 2)
        let initialSeed = track.rawValue.utf8.reduce(UInt64(1_469_598_103_934_665_603)) { ($0 ^ UInt64($1)) &* 1_099_511_628_211 }
        var noiseSeed = initialSeed | 1
        var smoothedNoise = 0.0
        let beatDuration = 60.0 / config.bpm
        let twoPi = Double.pi * 2

        for frame in 0..<frameCount {
            let time = Double(frame) / Double(sampleRate)
            let segment = min(Int(time / segmentDuration), chordFrequencies.count - 1)
            let segmentTime = time - Double(segment) * segmentDuration
            let frequencies = chordFrequencies[segment]
            let edgeFade = min(1.0, min(segmentTime, segmentDuration - segmentTime) / 0.16)
            let slowBreath = 0.82 + 0.18 * sin(twoPi * time / 7.5 + config.phase)

            var padLeft = 0.0
            var padRight = 0.0
            for (index, frequency) in frequencies.enumerated() {
                let weight = index == 0 ? 0.42 : 0.24
                let octave = index == 0 ? frequency * 0.5 : frequency
                padLeft += sin(twoPi * octave * time + Double(index) * 0.17) * weight
                padRight += sin(twoPi * octave * time + Double(index) * 0.17 + 0.035 + config.phase * 0.01) * weight
                padLeft += sin(twoPi * octave * 2 * time + 0.3) * weight * config.brightness
                padRight += sin(twoPi * octave * 2 * time + 0.36) * weight * config.brightness
            }
            padLeft *= edgeFade * slowBreath
            padRight *= edgeFade * slowBreath

            let beatIndex = Int(time / beatDuration)
            let beatTime = time - Double(beatIndex) * beatDuration
            let pluckFrequency = frequencies[beatIndex % frequencies.count] * 2.0
            let pluckAttack = min(1.0, beatTime / 0.012)
            let pluckEnvelope = pluckAttack * exp(-5.2 * beatTime)
            let pluck = (sin(twoPi * pluckFrequency * beatTime) + 0.22 * sin(twoPi * pluckFrequency * 2 * beatTime)) * pluckEnvelope * config.pluck

            noiseSeed = noiseSeed &* 6_364_136_223_846_793_005 &+ 1_442_695_040_888_963_407
            let rawNoise = Double(Int32(bitPattern: UInt32(truncatingIfNeeded: noiseSeed >> 32))) / Double(Int32.max)
            smoothedNoise += (rawNoise - smoothedNoise) * 0.035
            let air = smoothedNoise * config.air

            let loopFadeFrames = Double(sampleRate) * 0.10
            let loopFade = min(1.0, min(Double(frame), Double(frameCount - 1 - frame)) / loopFadeFrames)
            let pan = 0.5 + 0.12 * sin(twoPi * time / 11.0 + config.phase)
            let leftGain = sqrt(max(0.0, 1.0 - pan))
            let rightGain = sqrt(max(0.0, pan))
            let master = 0.23 * loopFade
            samples[frame * 2] = pcm16((padLeft * leftGain + pluck * 0.82 + air) * master)
            samples[frame * 2 + 1] = pcm16((padRight * rightGain + pluck + air * 0.94) * master)
        }
        return waveData(samples: samples, sampleRate: sampleRate)
    }

    private static func midiFrequency(_ note: Int) -> Double { 440.0 * pow(2.0, Double(note - 69) / 12.0) }
    private static func pcm16(_ value: Double) -> Int16 { Int16((min(max(value, -1), 1) * Double(Int16.max)).rounded()) }

    private static func waveData(samples: [Int16], sampleRate: Int) -> Data {
        let channels: UInt16 = 2
        let bitsPerSample: UInt16 = 16
        let bytesPerSample = UInt32(bitsPerSample / 8)
        let dataByteCount = UInt32(samples.count) * bytesPerSample
        var result = Data(); result.reserveCapacity(Int(44 + dataByteCount))
        func ascii(_ value: String) { result.append(contentsOf: value.utf8) }
        func u16(_ value: UInt16) { var little = value.littleEndian; withUnsafeBytes(of: &little) { result.append(contentsOf: $0) } }
        func u32(_ value: UInt32) { var little = value.littleEndian; withUnsafeBytes(of: &little) { result.append(contentsOf: $0) } }
        ascii("RIFF"); u32(36 + dataByteCount); ascii("WAVE"); ascii("fmt "); u32(16); u16(1); u16(channels)
        u32(UInt32(sampleRate)); u32(UInt32(sampleRate) * UInt32(channels) * bytesPerSample); u16(channels * UInt16(bytesPerSample)); u16(bitsPerSample)
        ascii("data"); u32(dataByteCount)
        samples.withUnsafeBufferPointer { result.append(Data(buffer: $0)) }
        return result
    }
}

@MainActor
final class FocusMusicPlayer: ObservableObject {
    private enum DefaultsKey {
        static let track = "vertex.focusMusic.track.v1"
        static let volume = "vertex.focusMusic.volume.v1"
    }

    @Published private(set) var selectedTrack: FocusMusicTrack
    @Published private(set) var isPlaying = false
    @Published private(set) var isPreparing = false
    @Published private(set) var volume: Double
    @Published private(set) var errorMessage: String?

    private var audioPlayer: AVAudioPlayer?
    private var loadedTrack: FocusMusicTrack?
    private var renderGeneration = 0
    private let defaults: UserDefaults

    init(defaults: UserDefaults = .standard) {
        self.defaults = defaults
        selectedTrack = FocusMusicTrack(rawValue: defaults.string(forKey: DefaultsKey.track) ?? "") ?? .quietDesk
        volume = defaults.object(forKey: DefaultsKey.volume) == nil ? 0.32 : min(max(defaults.double(forKey: DefaultsKey.volume), 0), 0.8)
    }

    func togglePlayback() {
        if isPlaying { audioPlayer?.pause(); isPlaying = false; return }
        if loadedTrack == selectedTrack, let audioPlayer {
            do {
                try activateSession()
                audioPlayer.volume = Float(volume)
                guard audioPlayer.play() else { throw FocusMusicError.couldNotStart }
                isPlaying = true; errorMessage = nil
            } catch { isPlaying = false; errorMessage = error.localizedDescription }
            return
        }
        prepare(track: selectedTrack, autoPlay: true)
    }

    func select(_ track: FocusMusicTrack) {
        guard track != selectedTrack else { return }
        selectedTrack = track; defaults.set(track.rawValue, forKey: DefaultsKey.track)
        let shouldContinue = isPlaying
        if shouldContinue { audioPlayer?.stop(); isPlaying = false; prepare(track: track, autoPlay: true) }
    }

    func selectNext() { let tracks = FocusMusicTrack.allCases; guard let i = tracks.firstIndex(of: selectedTrack) else { return }; select(tracks[(i + 1) % tracks.count]) }
    func selectPrevious() { let tracks = FocusMusicTrack.allCases; guard let i = tracks.firstIndex(of: selectedTrack) else { return }; select(tracks[(i - 1 + tracks.count) % tracks.count]) }
    func setVolume(_ newValue: Double) { volume = min(max(newValue, 0), 0.8); audioPlayer?.volume = Float(volume); defaults.set(volume, forKey: DefaultsKey.volume) }

    private func prepare(track: FocusMusicTrack, autoPlay: Bool) {
        renderGeneration += 1; let generation = renderGeneration; isPreparing = true; errorMessage = nil
        Task { [weak self] in
            let data = await Task.detached(priority: .utility) { FocusMusicSynthesizer.render(track: track) }.value
            guard let self, generation == self.renderGeneration else { return }
            do {
                let player = try AVAudioPlayer(data: data)
                player.numberOfLoops = -1; player.volume = Float(self.volume)
                guard player.prepareToPlay() else { throw FocusMusicError.couldNotPrepare }
                self.audioPlayer?.stop(); self.audioPlayer = player; self.loadedTrack = track; self.isPreparing = false
                if autoPlay {
                    try self.activateSession()
                    guard player.play() else { throw FocusMusicError.couldNotStart }
                    self.isPlaying = true
                }
            } catch { self.isPreparing = false; self.isPlaying = false; self.errorMessage = error.localizedDescription }
        }
    }

    private func activateSession() throws {
        let session = AVAudioSession.sharedInstance()
        try session.setCategory(FocusMusicPlaybackPolicy.category, mode: .default, options: FocusMusicPlaybackPolicy.options)
        try session.setActive(true)
    }
}
