import Foundation
public enum ExpandedEffectParameterID {
    public static let amount = "amount"
    public static let angle = "angle"
    public static let centerStretch = "centerStretch"
    public static let centerX = "centerX"
    public static let centerY = "centerY"
    public static let chroma = "chroma"
    public static let contrast = "contrast"
    public static let count = "count"
    public static let cropAmount = "cropAmount"
    public static let decay = "decay"
    public static let edgeIntensity = "edgeIntensity"
    public static let focusPosition = "focusPosition"
    public static let focusWidth = "focusWidth"
    public static let frequency = "frequency"
    public static let height = "height"
    public static let inset = "inset"
    public static let intensity = "intensity"
    public static let length = "length"
    public static let maximum = "maximum"
    public static let minimum = "minimum"
    public static let noiseLevel = "noiseLevel"
    public static let periodicity = "periodicity"
    public static let radius = "radius"
    public static let refraction = "refraction"
    public static let ringAmount = "ringAmount"
    public static let ringSize = "ringSize"
    public static let rotation = "rotation"
    public static let saturation = "saturation"
    public static let scale = "scale"
    public static let sharpness = "sharpness"
    public static let size = "size"
    public static let softness = "softness"
    public static let strands = "strands"
    public static let temperature = "temperature"
    public static let threshold = "threshold"
    public static let tint = "tint"
    public static let width = "width"
    public static let zoom = "zoom"
    public static let seed = "seed"
    public static let birthRate = "birthRate"
    public static let lifetime = "lifetime"
    public static let speed = "speed"
    public static let gravity = "gravity"
    public static let turbulence = "turbulence"
    public static let density = "density"
    public static let hue = "hue"
}

enum ProjectEffectExpansionDescriptors {
    private static func scalar(_ id: String, _ name: String, _ value: Double, _ range: ClosedRange<Double>, help: String = "") -> ProjectEffectParameterDescriptor {
        .init(id: id, displayName: name, defaultValue: .scalar(value), domain: .scalar(range), help: help)
    }

    private static func descriptor(_ type: ProjectEffectType, _ name: String, _ category: ProjectEffectCategory, keywords: [String], summary: String, parameters: [ProjectEffectParameterDescriptor] = []) -> ProjectEffectDescriptor {
        .init(type: type, displayName: name, category: category, executionMode: .nativePixel, keywords: keywords, summary: summary, parameters: parameters)
    }

    static let all: [ProjectEffectDescriptor] = [
        descriptor(.discBlur, "Disc Blur", .blurAndSharpen, keywords: ["blur", "disc", "soften"], summary: "Disc Blur implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 10.0, 0.0...200.0)]),
        descriptor(.zoomBlur, "Zoom Blur", .blurAndSharpen, keywords: ["zoom", "radial", "blur"], summary: "Zoom Blur implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.amount, "Amount", 12.0, 0.0...200.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.bokehBlur, "Bokeh Blur", .blurAndSharpen, keywords: ["bokeh", "lens", "blur"], summary: "Bokeh Blur implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 12.0, 0.0...100.0), scalar(ExpandedEffectParameterID.ringAmount, "Ring Amount", 0.15, 0.0...1.0), scalar(ExpandedEffectParameterID.ringSize, "Ring Size", 0.1, 0.0...1.0), scalar(ExpandedEffectParameterID.softness, "Softness", 0.5, 0.0...1.0)]),
        descriptor(.unsharpMask, "Unsharp Mask", .blurAndSharpen, keywords: ["unsharp", "sharpen", "detail"], summary: "Unsharp Mask implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 2.5, 0.0...50.0), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.5, 0.0...2.0)]),
        descriptor(.morphologyGradient, "Morphology Gradient", .blurAndSharpen, keywords: ["morphology", "edge", "cleanup"], summary: "Morphology Gradient implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 3.0, 0.0...50.0)]),
        descriptor(.morphologyMinimum, "Morphology Minimum", .blurAndSharpen, keywords: ["morphology", "edge", "cleanup"], summary: "Morphology Minimum implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 3.0, 0.0...50.0)]),
        descriptor(.morphologyMaximum, "Morphology Maximum", .blurAndSharpen, keywords: ["morphology", "edge", "cleanup"], summary: "Morphology Maximum implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 3.0, 0.0...50.0)]),
        descriptor(.morphologyRectangleMinimum, "Morphology Rectangle Minimum", .blurAndSharpen, keywords: ["morphology", "rectangle", "cleanup"], summary: "Morphology Rectangle Minimum implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.width, "Width", 5.0, 1.0...100.0), scalar(ExpandedEffectParameterID.height, "Height", 5.0, 1.0...100.0)]),
        descriptor(.morphologyRectangleMaximum, "Morphology Rectangle Maximum", .blurAndSharpen, keywords: ["morphology", "rectangle", "cleanup"], summary: "Morphology Rectangle Maximum implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.width, "Width", 5.0, 1.0...100.0), scalar(ExpandedEffectParameterID.height, "Height", 5.0, 1.0...100.0)]),
        descriptor(.temperatureTint, "Temperature & Tint", .colorCorrection, keywords: ["temperature", "tint", "white balance"], summary: "Temperature & Tint implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.temperature, "Temperature", 6500.0, 2000.0...12000.0), scalar(ExpandedEffectParameterID.tint, "Tint", 0.0, -150.0...150.0)]),
        descriptor(.colorMonochrome, "Monochrome", .colorCorrection, keywords: ["monochrome", "black white", "tint"], summary: "Monochrome implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.intensity, "Intensity", 1.0, 0.0...1.0)]),
        descriptor(.colorClamp, "Color Clamp", .channel, keywords: ["clamp", "channel", "range"], summary: "Color Clamp implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.minimum, "Minimum", 0.0, 0.0...1.0), scalar(ExpandedEffectParameterID.maximum, "Maximum", 1.0, 0.0...1.0)]),
        descriptor(.photoChrome, "Photo Chrome", .colorCorrection, keywords: ["photo", "look", "color"], summary: "Photo Chrome implemented on Vertex2's native preview/export effect path.", parameters: []),
        descriptor(.photoFade, "Photo Fade", .colorCorrection, keywords: ["photo", "look", "color"], summary: "Photo Fade implemented on Vertex2's native preview/export effect path.", parameters: []),
        descriptor(.photoInstant, "Photo Instant", .colorCorrection, keywords: ["photo", "look", "color"], summary: "Photo Instant implemented on Vertex2's native preview/export effect path.", parameters: []),
        descriptor(.photoMono, "Photo Mono", .colorCorrection, keywords: ["photo", "look", "color"], summary: "Photo Mono implemented on Vertex2's native preview/export effect path.", parameters: []),
        descriptor(.photoNoir, "Photo Noir", .colorCorrection, keywords: ["photo", "look", "color"], summary: "Photo Noir implemented on Vertex2's native preview/export effect path.", parameters: []),
        descriptor(.photoProcess, "Photo Process", .colorCorrection, keywords: ["photo", "look", "color"], summary: "Photo Process implemented on Vertex2's native preview/export effect path.", parameters: []),
        descriptor(.photoTonal, "Photo Tonal", .colorCorrection, keywords: ["photo", "look", "color"], summary: "Photo Tonal implemented on Vertex2's native preview/export effect path.", parameters: []),
        descriptor(.photoTransfer, "Photo Transfer", .colorCorrection, keywords: ["photo", "look", "color"], summary: "Photo Transfer implemented on Vertex2's native preview/export effect path.", parameters: []),
        descriptor(.linearToSRGB, "Linear to sRGB", .colorCorrection, keywords: ["photo", "look", "color"], summary: "Linear to sRGB implemented on Vertex2's native preview/export effect path.", parameters: []),
        descriptor(.sRGBToLinear, "sRGB to Linear", .colorCorrection, keywords: ["photo", "look", "color"], summary: "sRGB to Linear implemented on Vertex2's native preview/export effect path.", parameters: []),
        descriptor(.colorThreshold, "Color Threshold", .channel, keywords: ["threshold", "matte", "channel"], summary: "Color Threshold implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.threshold, "Threshold", 0.5, 0.0...1.0)]),
        descriptor(.colorThresholdOtsu, "Otsu Threshold", .channel, keywords: ["threshold", "otsu", "matte"], summary: "Otsu Threshold implemented on Vertex2's native preview/export effect path.", parameters: []),
        descriptor(.crystallize, "Crystallize", .stylize, keywords: ["crystal", "cells", "stylize"], summary: "Crystallize implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Cell Size", 20.0, 1.0...200.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.edgeWork, "Edge Work", .stylize, keywords: ["edge", "outline", "stylize"], summary: "Edge Work implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 3.0, 0.0...50.0)]),
        descriptor(.gloom, "Gloom", .stylize, keywords: ["gloom", "bloom", "soft"], summary: "Gloom implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 10.0, 0.0...100.0), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.5, 0.0...2.0)]),
        descriptor(.hexagonalPixelate, "Hexagonal Pixelate", .stylize, keywords: ["hex", "pixelate", "mosaic"], summary: "Hexagonal Pixelate implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.scale, "Scale", 12.0, 1.0...200.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.lineOverlay, "Line Overlay", .stylize, keywords: ["line", "outline", "comic"], summary: "Line Overlay implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.noiseLevel, "Noise Level", 0.07, 0.0...1.0), scalar(ExpandedEffectParameterID.sharpness, "Sharpness", 0.7, 0.0...2.0), scalar(ExpandedEffectParameterID.edgeIntensity, "Edge Intensity", 1.0, 0.0...5.0), scalar(ExpandedEffectParameterID.threshold, "Threshold", 0.1, 0.0...1.0), scalar(ExpandedEffectParameterID.contrast, "Contrast", 50.0, 0.0...200.0)]),
        descriptor(.pointillize, "Pointillize", .stylize, keywords: ["point", "dots", "stylize"], summary: "Pointillize implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 10.0, 1.0...100.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.circularScreen, "Circular Screen", .stylize, keywords: ["halftone", "screen", "print"], summary: "Circular Screen implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.width, "Width", 6.0, 1.0...100.0), scalar(ExpandedEffectParameterID.sharpness, "Sharpness", 0.7, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.dotScreen, "Dot Screen", .stylize, keywords: ["halftone", "screen", "print"], summary: "Dot Screen implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.width, "Width", 6.0, 1.0...100.0), scalar(ExpandedEffectParameterID.sharpness, "Sharpness", 0.7, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.hatchedScreen, "Hatched Screen", .stylize, keywords: ["halftone", "screen", "print"], summary: "Hatched Screen implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.width, "Width", 6.0, 1.0...100.0), scalar(ExpandedEffectParameterID.sharpness, "Sharpness", 0.7, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.lineScreen, "Line Screen", .stylize, keywords: ["halftone", "screen", "print"], summary: "Line Screen implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.width, "Width", 6.0, 1.0...100.0), scalar(ExpandedEffectParameterID.sharpness, "Sharpness", 0.7, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.cmykHalftone, "CMYK Halftone", .stylize, keywords: ["cmyk", "halftone", "print"], summary: "CMYK Halftone implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.width, "Width", 6.0, 1.0...100.0), scalar(ExpandedEffectParameterID.sharpness, "Sharpness", 0.7, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.depthOfField, "Depth of Field", .blurAndSharpen, keywords: ["depth", "focus", "lens", "blur"], summary: "Depth of Field implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.focusPosition, "Focus Position", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.focusWidth, "Focus Width", 0.25, 0.01...1.0), scalar(ExpandedEffectParameterID.radius, "Blur Radius", 10.0, 0.0...100.0), scalar(ExpandedEffectParameterID.saturation, "Saturation", 1.0, 0.0...2.0)]),
        descriptor(.bumpDistortion, "Bump Distortion", .distort, keywords: ["bump", "warp", "lens"], summary: "Bump Distortion implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 300.0, 0.0...2000.0), scalar(ExpandedEffectParameterID.scale, "Scale", 0.5, -1.0...1.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.bumpLinear, "Linear Bump", .distort, keywords: ["bump", "linear", "warp"], summary: "Linear Bump implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 300.0, 0.0...2000.0), scalar(ExpandedEffectParameterID.scale, "Scale", 0.5, -1.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.circleSplash, "Circle Splash", .distort, keywords: ["circle", "splash", "warp"], summary: "Circle Splash implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 300.0, 0.0...2000.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.circularWrap, "Circular Wrap", .distort, keywords: ["circular", "wrap", "warp"], summary: "Circular Wrap implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 300.0, 0.0...2000.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -360.0...360.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.droste, "Droste", .distort, keywords: ["droste", "recursive", "spiral"], summary: "Droste implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.inset, "Inset", 0.2, 0.01...0.49), scalar(ExpandedEffectParameterID.strands, "Strands", 1.0, -10.0...10.0), scalar(ExpandedEffectParameterID.periodicity, "Periodicity", 1.0, -10.0...10.0), scalar(ExpandedEffectParameterID.rotation, "Rotation", 0.0, -360.0...360.0), scalar(ExpandedEffectParameterID.zoom, "Zoom", 1.0, 0.1...5.0)]),
        descriptor(.holeDistortion, "Hole Distortion", .distort, keywords: ["hole", "warp", "distort"], summary: "Hole Distortion implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 150.0, 0.0...2000.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.lightTunnel, "Light Tunnel", .distort, keywords: ["tunnel", "warp", "light"], summary: "Light Tunnel implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 100.0, 0.0...1000.0), scalar(ExpandedEffectParameterID.rotation, "Rotation", 0.0, -360.0...360.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.pinchDistortion, "Pinch Distortion", .distort, keywords: ["pinch", "warp", "distort"], summary: "Pinch Distortion implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 300.0, 0.0...2000.0), scalar(ExpandedEffectParameterID.scale, "Scale", 0.5, -2.0...2.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.stretchCrop, "Stretch Crop", .distort, keywords: ["stretch", "crop", "distort"], summary: "Stretch Crop implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.centerStretch, "Center Stretch", 0.25, 0.0...1.0), scalar(ExpandedEffectParameterID.cropAmount, "Crop Amount", 0.25, 0.0...1.0)]),
        descriptor(.torusLens, "Torus Lens", .distort, keywords: ["torus", "lens", "refraction"], summary: "Torus Lens implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 160.0, 0.0...1000.0), scalar(ExpandedEffectParameterID.width, "Width", 80.0, 0.0...500.0), scalar(ExpandedEffectParameterID.refraction, "Refraction", 0.7, -5.0...5.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.vortexDistortion, "Vortex Distortion", .distort, keywords: ["vortex", "swirl", "warp"], summary: "Vortex Distortion implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 300.0, 0.0...2000.0), scalar(ExpandedEffectParameterID.angle, "Angle", 90.0, -720.0...720.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.glassLozenge, "Glass Lozenge", .distort, keywords: ["glass", "lens", "refraction"], summary: "Glass Lozenge implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.length, "Length", 300.0, 1.0...2000.0), scalar(ExpandedEffectParameterID.radius, "Radius", 80.0, 0.0...500.0), scalar(ExpandedEffectParameterID.refraction, "Refraction", 1.7, -5.0...5.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0)]),
        descriptor(.kaleidoscope, "Kaleidoscope", .tile, keywords: ["tile", "repeat", "kaleidoscope"], summary: "Kaleidoscope implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.width, "Width", 100.0, 1.0...1000.0), scalar(ExpandedEffectParameterID.count, "Count", 6.0, 1.0...64.0)]),
        descriptor(.opTile, "Op Tile", .tile, keywords: ["tile", "repeat", "kaleidoscope"], summary: "Op Tile implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.width, "Width", 100.0, 1.0...1000.0)]),
        descriptor(.triangleKaleidoscope, "Triangle Kaleidoscope", .tile, keywords: ["tile", "repeat", "kaleidoscope"], summary: "Triangle Kaleidoscope implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.width, "Width", 100.0, 1.0...1000.0), scalar(ExpandedEffectParameterID.rotation, "Rotation", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.decay, "Decay", 0.85, 0.0...1.0)]),
        descriptor(.sixfoldReflectedTile, "Sixfold Reflected Tile", .tile, keywords: ["tile", "repeat", "kaleidoscope"], summary: "Sixfold Reflected Tile implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.width, "Width", 100.0, 1.0...1000.0)]),
        descriptor(.twelvefoldReflectedTile, "Twelvefold Reflected Tile", .tile, keywords: ["tile", "repeat", "kaleidoscope"], summary: "Twelvefold Reflected Tile implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.width, "Width", 100.0, 1.0...1000.0)]),
        descriptor(.parallelogramTile, "Parallelogram Tile", .tile, keywords: ["tile", "repeat", "kaleidoscope"], summary: "Parallelogram Tile implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.width, "Width", 100.0, 1.0...1000.0)]),
        descriptor(.triangleTile, "Triangle Tile", .tile, keywords: ["tile", "repeat", "kaleidoscope"], summary: "Triangle Tile implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.width, "Width", 100.0, 1.0...1000.0)]),
        descriptor(.fourfoldReflectedTile, "Fourfold Reflected Tile", .tile, keywords: ["tile", "repeat", "kaleidoscope"], summary: "Fourfold Reflected Tile implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.width, "Width", 100.0, 1.0...1000.0)]),
        descriptor(.fourfoldRotatedTile, "Fourfold Rotated Tile", .tile, keywords: ["tile", "repeat", "kaleidoscope"], summary: "Fourfold Rotated Tile implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.width, "Width", 100.0, 1.0...1000.0)]),
        descriptor(.fourfoldTranslatedTile, "Fourfold Translated Tile", .tile, keywords: ["tile", "repeat", "kaleidoscope"], summary: "Fourfold Translated Tile implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.width, "Width", 100.0, 1.0...1000.0)]),
        descriptor(.eightfoldReflectedTile, "Eightfold Reflected Tile", .tile, keywords: ["tile", "repeat", "kaleidoscope"], summary: "Eightfold Reflected Tile implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.width, "Width", 100.0, 1.0...1000.0)]),
        descriptor(.glideReflectedTile, "Glide Reflected Tile", .tile, keywords: ["tile", "repeat", "kaleidoscope"], summary: "Glide Reflected Tile implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.width, "Width", 100.0, 1.0...1000.0)]),
        descriptor(.sixfoldRotatedTile, "Sixfold Rotated Tile", .tile, keywords: ["tile", "repeat", "kaleidoscope"], summary: "Sixfold Rotated Tile implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0), scalar(ExpandedEffectParameterID.width, "Width", 100.0, 1.0...1000.0)]),
        descriptor(.vertexAuraGlow, "Vertex Aura Glow", .stylize, keywords: ["vertex", "glow", "bloom", "aura"], summary: "Vertex-owned highlight bloom using independently implemented threshold, blur, and additive/screen compositing.", parameters: [scalar(ExpandedEffectParameterID.threshold, "Threshold", 0.65, 0.0...1.0), scalar(ExpandedEffectParameterID.radius, "Radius", 24.0, 0.0...200.0), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.8, 0.0...3.0)]),
        descriptor(.vertexDarkGlow, "Vertex Dark Bloom", .stylize, keywords: ["vertex", "dark bloom", "shadow glow"], summary: "Vertex-owned dark-region bloom using independently implemented luma selection and soft compositing.", parameters: [scalar(ExpandedEffectParameterID.threshold, "Dark Threshold", 0.35, 0.0...1.0), scalar(ExpandedEffectParameterID.radius, "Radius", 20.0, 0.0...200.0), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.6, 0.0...3.0)]),
        descriptor(.vertexEdgeGlow, "Vertex Edge Radiance", .stylize, keywords: ["vertex", "edge", "radiance", "neon"], summary: "Vertex-owned edge extraction and bloom chain for radiant outlines.", parameters: [scalar(ExpandedEffectParameterID.radius, "Radius", 12.0, 0.0...100.0), scalar(ExpandedEffectParameterID.intensity, "Intensity", 1.0, 0.0...3.0)]),
        descriptor(.vertexHalation, "Vertex Halation", .stylize, keywords: ["vertex", "halation", "film", "red"], summary: "Vertex-owned warm highlight spill inspired by optical film halation.", parameters: [scalar(ExpandedEffectParameterID.threshold, "Threshold", 0.7, 0.0...1.0), scalar(ExpandedEffectParameterID.radius, "Radius", 18.0, 0.0...150.0), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.5, 0.0...2.0)]),
        descriptor(.vertexFilmGrain, "Vertex Film Grain", .stylize, keywords: ["vertex", "film", "grain", "noise"], summary: "Vertex-owned procedural film-grain treatment generated locally without bundled third-party assets.", parameters: [scalar(ExpandedEffectParameterID.amount, "Amount", 0.12, 0.0...1.0), scalar(ExpandedEffectParameterID.size, "Size", 1.0, 1.0...8.0), scalar(ExpandedEffectParameterID.chroma, "Chroma", 0.15, 0.0...1.0)]),
        descriptor(.vertexScanlines, "Vertex Scanlines", .stylize, keywords: ["vertex", "scanline", "crt", "retro"], summary: "Vertex-owned procedural scanline overlay for CRT and display treatments.", parameters: [scalar(ExpandedEffectParameterID.frequency, "Frequency", 2.0, 1.0...40.0), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.25, 0.0...1.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0)]),
        descriptor(.vertexRGBSplit, "Vertex RGB Split", .channel, keywords: ["vertex", "rgb", "split", "chromatic"], summary: "Vertex-owned channel separation using independent color matrices and spatial offsets.", parameters: [scalar(ExpandedEffectParameterID.amount, "Offset", 6.0, 0.0...100.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0)]),
        descriptor(.vertexPrismBlur, "Vertex Prism Blur", .blurAndSharpen, keywords: ["vertex", "prism", "chromatic", "blur"], summary: "Vertex-owned chromatic split and blur chain for prismatic lens looks.", parameters: [scalar(ExpandedEffectParameterID.amount, "Chromatic Offset", 8.0, 0.0...100.0), scalar(ExpandedEffectParameterID.radius, "Blur Radius", 4.0, 0.0...50.0), scalar(ExpandedEffectParameterID.angle, "Angle", 0.0, -180.0...180.0)]),
        descriptor(.vertexLightLeak, "Vertex Light Leak", .stylize, keywords: ["vertex", "light leak", "film", "flare"], summary: "Vertex-owned procedural radial light leak generated from Core Image gradients.", parameters: [scalar(ExpandedEffectParameterID.centerX, "Center X", 0.2, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.8, 0.0...1.0), scalar(ExpandedEffectParameterID.radius, "Radius", 500.0, 1.0...3000.0), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.7, 0.0...2.0)]),
        descriptor(.vertexSunRays, "Vertex Sun Rays", .stylize, keywords: ["vertex", "sun", "rays", "beams"], summary: "Vertex-owned light-ray composite using a procedural generator cropped to the source frame.", parameters: [scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.8, 0.0...2.0), scalar(ExpandedEffectParameterID.radius, "Radius", 120.0, 1.0...1000.0)]),
        descriptor(.lumaKey, "Luma Key", .keying, keywords: ["luma", "key", "matte", "alpha"], summary: "Luma Key implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.threshold, "Threshold", 0.5, 0.0...1.0), scalar(ExpandedEffectParameterID.softness, "Softness", 0.05, 0.0...0.5)]),
        descriptor(.brightMatte, "Bright Matte", .keying, keywords: ["bright", "matte", "luma", "mask"], summary: "Bright Matte implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.threshold, "Threshold", 0.65, 0.0...1.0), scalar(ExpandedEffectParameterID.softness, "Softness", 0.05, 0.0...0.5)]),
        descriptor(.darkMatte, "Dark Matte", .keying, keywords: ["dark", "matte", "luma", "mask"], summary: "Dark Matte implemented on Vertex2's native preview/export effect path.", parameters: [scalar(ExpandedEffectParameterID.threshold, "Threshold", 0.35, 0.0...1.0), scalar(ExpandedEffectParameterID.softness, "Softness", 0.05, 0.0...0.5)]),
        descriptor(.vertexParticleEmitter, "Vertex Particle Emitter", .stylize, keywords: ["particle", "emitter", "birth", "velocity"], summary: "Vertex-owned deterministic GPU particle simulation evaluated from exact composition time.", parameters: [scalar(ExpandedEffectParameterID.seed, "Seed", 17, 1...9999), scalar(ExpandedEffectParameterID.birthRate, "Birth Rate", 52, 1...240), scalar(ExpandedEffectParameterID.lifetime, "Lifetime", 3.2, 0.2...12), scalar(ExpandedEffectParameterID.size, "Size", 7, 1...80), scalar(ExpandedEffectParameterID.speed, "Speed", 0.24, 0...2), scalar(ExpandedEffectParameterID.gravity, "Gravity", 0.12, -2...2), scalar(ExpandedEffectParameterID.turbulence, "Turbulence", 0.2, 0...2), scalar(ExpandedEffectParameterID.density, "Density", 0.55, 0.05...1), scalar(ExpandedEffectParameterID.hue, "Hue", 0.58, 0...1), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.8, 0...2), scalar(ExpandedEffectParameterID.angle, "Angle", 0, -180...180), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0...1), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0...1)]),
        descriptor(.vertexParticleTrails, "Vertex Particle Trails", .stylize, keywords: ["particle", "trails", "motion", "streaks"], summary: "Vertex-owned deterministic GPU particle simulation evaluated from exact composition time.", parameters: [scalar(ExpandedEffectParameterID.seed, "Seed", 17, 1...9999), scalar(ExpandedEffectParameterID.birthRate, "Birth Rate", 52, 1...240), scalar(ExpandedEffectParameterID.lifetime, "Lifetime", 3.2, 0.2...12), scalar(ExpandedEffectParameterID.size, "Size", 7, 1...80), scalar(ExpandedEffectParameterID.speed, "Speed", 0.24, 0...2), scalar(ExpandedEffectParameterID.gravity, "Gravity", 0.12, -2...2), scalar(ExpandedEffectParameterID.turbulence, "Turbulence", 0.2, 0...2), scalar(ExpandedEffectParameterID.density, "Density", 0.55, 0.05...1), scalar(ExpandedEffectParameterID.hue, "Hue", 0.58, 0...1), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.8, 0...2), scalar(ExpandedEffectParameterID.angle, "Angle", 0, -180...180), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0...1), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0...1)]),
        descriptor(.vertexParticleBurst, "Vertex Particle Burst", .stylize, keywords: ["particle", "burst", "radial"], summary: "Vertex-owned deterministic GPU particle simulation evaluated from exact composition time.", parameters: [scalar(ExpandedEffectParameterID.seed, "Seed", 17, 1...9999), scalar(ExpandedEffectParameterID.birthRate, "Birth Rate", 52, 1...240), scalar(ExpandedEffectParameterID.lifetime, "Lifetime", 3.2, 0.2...12), scalar(ExpandedEffectParameterID.size, "Size", 7, 1...80), scalar(ExpandedEffectParameterID.speed, "Speed", 0.24, 0...2), scalar(ExpandedEffectParameterID.gravity, "Gravity", 0.12, -2...2), scalar(ExpandedEffectParameterID.turbulence, "Turbulence", 0.2, 0...2), scalar(ExpandedEffectParameterID.density, "Density", 0.55, 0.05...1), scalar(ExpandedEffectParameterID.hue, "Hue", 0.58, 0...1), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.8, 0...2), scalar(ExpandedEffectParameterID.angle, "Angle", 0, -180...180), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0...1), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0...1)]),
        descriptor(.vertexParticleSnow, "Vertex Particle Snow", .stylize, keywords: ["particle", "snow", "falling"], summary: "Vertex-owned deterministic GPU particle simulation evaluated from exact composition time.", parameters: [scalar(ExpandedEffectParameterID.seed, "Seed", 17, 1...9999), scalar(ExpandedEffectParameterID.birthRate, "Birth Rate", 52, 1...240), scalar(ExpandedEffectParameterID.lifetime, "Lifetime", 3.2, 0.2...12), scalar(ExpandedEffectParameterID.size, "Size", 7, 1...80), scalar(ExpandedEffectParameterID.speed, "Speed", 0.24, 0...2), scalar(ExpandedEffectParameterID.gravity, "Gravity", 0.12, -2...2), scalar(ExpandedEffectParameterID.turbulence, "Turbulence", 0.2, 0...2), scalar(ExpandedEffectParameterID.density, "Density", 0.55, 0.05...1), scalar(ExpandedEffectParameterID.hue, "Hue", 0.58, 0...1), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.8, 0...2), scalar(ExpandedEffectParameterID.angle, "Angle", 0, -180...180), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0...1), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0...1)]),
        descriptor(.vertexFractalNoise, "Vertex Fractal Noise", .stylize, keywords: ["fractal", "noise", "procedural"], summary: "Vertex-owned deterministic GPU procedural generator evaluated from exact composition time.", parameters: [scalar(ExpandedEffectParameterID.seed, "Seed", 17, 1...9999), scalar(ExpandedEffectParameterID.scale, "Scale", 24, 1...120), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.8, 0...2), scalar(ExpandedEffectParameterID.hue, "Hue", 0.58, 0...1), scalar(ExpandedEffectParameterID.angle, "Angle", 0, -180...180), scalar(ExpandedEffectParameterID.density, "Density", 0.55, 0.05...1), scalar(ExpandedEffectParameterID.size, "Size", 7, 1...80), scalar(ExpandedEffectParameterID.turbulence, "Turbulence", 0.2, 0...2), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0...1), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0...1)]),
        descriptor(.vertexTurbulenceField, "Vertex Turbulence Field", .stylize, keywords: ["turbulence", "field", "procedural"], summary: "Vertex-owned deterministic GPU procedural generator evaluated from exact composition time.", parameters: [scalar(ExpandedEffectParameterID.seed, "Seed", 17, 1...9999), scalar(ExpandedEffectParameterID.scale, "Scale", 24, 1...120), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.8, 0...2), scalar(ExpandedEffectParameterID.hue, "Hue", 0.58, 0...1), scalar(ExpandedEffectParameterID.angle, "Angle", 0, -180...180), scalar(ExpandedEffectParameterID.density, "Density", 0.55, 0.05...1), scalar(ExpandedEffectParameterID.size, "Size", 7, 1...80), scalar(ExpandedEffectParameterID.turbulence, "Turbulence", 0.2, 0...2), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0...1), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0...1)]),
        descriptor(.vertexProceduralGrid, "Vertex Procedural Grid", .stylize, keywords: ["grid", "procedural"], summary: "Vertex-owned deterministic GPU procedural generator evaluated from exact composition time.", parameters: [scalar(ExpandedEffectParameterID.seed, "Seed", 17, 1...9999), scalar(ExpandedEffectParameterID.scale, "Scale", 24, 1...120), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.8, 0...2), scalar(ExpandedEffectParameterID.hue, "Hue", 0.58, 0...1), scalar(ExpandedEffectParameterID.angle, "Angle", 0, -180...180), scalar(ExpandedEffectParameterID.density, "Density", 0.55, 0.05...1), scalar(ExpandedEffectParameterID.size, "Size", 7, 1...80), scalar(ExpandedEffectParameterID.turbulence, "Turbulence", 0.2, 0...2), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0...1), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0...1)]),
        descriptor(.vertexProceduralRays, "Vertex Procedural Rays", .stylize, keywords: ["rays", "beams", "procedural"], summary: "Vertex-owned deterministic GPU procedural generator evaluated from exact composition time.", parameters: [scalar(ExpandedEffectParameterID.seed, "Seed", 17, 1...9999), scalar(ExpandedEffectParameterID.scale, "Scale", 24, 1...120), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.8, 0...2), scalar(ExpandedEffectParameterID.hue, "Hue", 0.58, 0...1), scalar(ExpandedEffectParameterID.angle, "Angle", 0, -180...180), scalar(ExpandedEffectParameterID.density, "Density", 0.55, 0.05...1), scalar(ExpandedEffectParameterID.size, "Size", 7, 1...80), scalar(ExpandedEffectParameterID.turbulence, "Turbulence", 0.2, 0...2), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0...1), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0...1)]),
        descriptor(.vertexProceduralDots, "Vertex Procedural Dots", .stylize, keywords: ["dots", "pattern", "procedural"], summary: "Vertex-owned deterministic GPU procedural generator evaluated from exact composition time.", parameters: [scalar(ExpandedEffectParameterID.seed, "Seed", 17, 1...9999), scalar(ExpandedEffectParameterID.scale, "Scale", 24, 1...120), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.8, 0...2), scalar(ExpandedEffectParameterID.hue, "Hue", 0.58, 0...1), scalar(ExpandedEffectParameterID.angle, "Angle", 0, -180...180), scalar(ExpandedEffectParameterID.density, "Density", 0.55, 0.05...1), scalar(ExpandedEffectParameterID.size, "Size", 7, 1...80), scalar(ExpandedEffectParameterID.turbulence, "Turbulence", 0.2, 0...2), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0...1), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0...1)]),
        descriptor(.vertexPlasma, "Vertex Plasma", .stylize, keywords: ["plasma", "animated", "procedural"], summary: "Vertex-owned deterministic GPU procedural generator evaluated from exact composition time.", parameters: [scalar(ExpandedEffectParameterID.seed, "Seed", 17, 1...9999), scalar(ExpandedEffectParameterID.scale, "Scale", 24, 1...120), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.8, 0...2), scalar(ExpandedEffectParameterID.hue, "Hue", 0.58, 0...1), scalar(ExpandedEffectParameterID.angle, "Angle", 0, -180...180), scalar(ExpandedEffectParameterID.density, "Density", 0.55, 0.05...1), scalar(ExpandedEffectParameterID.size, "Size", 7, 1...80), scalar(ExpandedEffectParameterID.turbulence, "Turbulence", 0.2, 0...2), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0...1), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0...1)]),
        descriptor(.vertexVoronoi, "Vertex Voronoi", .stylize, keywords: ["voronoi", "cells", "procedural"], summary: "Vertex-owned deterministic GPU procedural generator evaluated from exact composition time.", parameters: [scalar(ExpandedEffectParameterID.seed, "Seed", 17, 1...9999), scalar(ExpandedEffectParameterID.scale, "Scale", 24, 1...120), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.8, 0...2), scalar(ExpandedEffectParameterID.hue, "Hue", 0.58, 0...1), scalar(ExpandedEffectParameterID.angle, "Angle", 0, -180...180), scalar(ExpandedEffectParameterID.density, "Density", 0.55, 0.05...1), scalar(ExpandedEffectParameterID.size, "Size", 7, 1...80), scalar(ExpandedEffectParameterID.turbulence, "Turbulence", 0.2, 0...2), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0...1), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0...1)]),
        descriptor(.vertexChecker, "Vertex Checker", .stylize, keywords: ["checkerboard", "procedural"], summary: "Vertex-owned deterministic GPU procedural generator evaluated from exact composition time.", parameters: [scalar(ExpandedEffectParameterID.seed, "Seed", 17, 1...9999), scalar(ExpandedEffectParameterID.scale, "Scale", 24, 1...120), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.8, 0...2), scalar(ExpandedEffectParameterID.hue, "Hue", 0.58, 0...1), scalar(ExpandedEffectParameterID.angle, "Angle", 0, -180...180), scalar(ExpandedEffectParameterID.density, "Density", 0.55, 0.05...1), scalar(ExpandedEffectParameterID.size, "Size", 7, 1...80), scalar(ExpandedEffectParameterID.turbulence, "Turbulence", 0.2, 0...2), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0...1), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0...1)]),
        descriptor(.vertexGradient, "Vertex Gradient", .stylize, keywords: ["gradient", "procedural"], summary: "Vertex-owned deterministic GPU procedural generator evaluated from exact composition time.", parameters: [scalar(ExpandedEffectParameterID.seed, "Seed", 17, 1...9999), scalar(ExpandedEffectParameterID.scale, "Scale", 24, 1...120), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.8, 0...2), scalar(ExpandedEffectParameterID.hue, "Hue", 0.58, 0...1), scalar(ExpandedEffectParameterID.angle, "Angle", 0, -180...180), scalar(ExpandedEffectParameterID.density, "Density", 0.55, 0.05...1), scalar(ExpandedEffectParameterID.size, "Size", 7, 1...80), scalar(ExpandedEffectParameterID.turbulence, "Turbulence", 0.2, 0...2), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0...1), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0...1)]),
        descriptor(.vertexStarField, "Vertex Star Field", .stylize, keywords: ["stars", "space", "procedural"], summary: "Vertex-owned deterministic GPU procedural generator evaluated from exact composition time.", parameters: [scalar(ExpandedEffectParameterID.seed, "Seed", 17, 1...9999), scalar(ExpandedEffectParameterID.scale, "Scale", 24, 1...120), scalar(ExpandedEffectParameterID.intensity, "Intensity", 0.8, 0...2), scalar(ExpandedEffectParameterID.hue, "Hue", 0.58, 0...1), scalar(ExpandedEffectParameterID.angle, "Angle", 0, -180...180), scalar(ExpandedEffectParameterID.density, "Density", 0.55, 0.05...1), scalar(ExpandedEffectParameterID.size, "Size", 7, 1...80), scalar(ExpandedEffectParameterID.turbulence, "Turbulence", 0.2, 0...2), scalar(ExpandedEffectParameterID.centerX, "Center X", 0.5, 0...1), scalar(ExpandedEffectParameterID.centerY, "Center Y", 0.5, 0...1)])
    ]
}
